### ISSUE TITLE
Feed stuck on _Int16ArrayView type

### ISSUE THREAD

**Issue by Fr1z** [chipweinberger/flutter_pcm_sound#40]
Hi there! I’ve noticed that in the latest version (3.1.7), every time I call:

`FlutterPcmSound.feed()`

I get this error:

>     Feed Error: type '_Int16ArrayView' is not a subtype of type 'Uint8List'

I’ve also tried feeding it with a zero-filled buffer with PcmArrayInt16.zeros()
but the error still occurs.

I’m testing on Android.

**Comment by chipweinberger** [comment]
please open a pr thank you

**Comment by chipweinberger** [comment]
i dont see any code that would break it. please find the exact commit that broke it

```
dependencies:
  flutter_pcm_sound:
    git:
      url: https://github.com/chipweinberger/flutter_pcm_sound.git
      ref: 1234567890abcdefg1345678
```
